### ISSUE TITLE
UK number may be 7 or 9 digits

### ISSUE THREAD

**Issue by keningharryscom** [AfterShip/phone#167]
Right now the code is limiting UK number to 10 digits, but some legit UK numbers are 7 or 9 digits.

https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom#cite_note-1

`7 for two special 08xx numbers; 9 in some 01xxx areas, one 01xxxx area, all 0500 numbers, and some 0800 numbers; 10 in all other areas`

Ideally the validation code can be more sophisticated to allow 7 digit only if the number is prefix with 08; and allow 9 digit only if the number is prefix with 01 or 0500 or 0800. But the current meta-data structure is not setup to do that. A simpler fix is to just extend the limits to consider 7 and 9 digits number legit for UK. Since this is front-end validation code, it is probably OK to be more relaxing and produce some false positive. Normally after front-end validaiton, this number will be sent to backend, and there's probably some more rigid backend validation.

**Comment by Bossa573** [comment]
According to Wikipedia,
mobile phone numbers start with `7`, which is the current setup: https://github.com/AfterShip/phone/blob/master/lib/iso3166Data.js#L627
and the page suggested that all the phone numbers start with `7` should be 10 digits excluding trunk code.

So if we add `7` and `9` to the length, it is valid for landlines or other phone numbers, but it conflicts with the `mobile_begin_with` setup.

(Because originally the module is designed for detecting mobile phone number, not for detecting landlines, the iso3166 metadata structure does not come with such a refined setup.)

**Comment by keningharryscom** [comment]
Thanks for the clarification. I wonder if there's a plan to extend the meta data format to accommodate this?

"Finding out whether a number is a mobile number or not" seems like a more complicated problem than checking the `mobile_begin_with` prefix. For example, I live in northern Virginia in the US, with area code 703 and 571 in my area, and those two area codes are listed in the `mobile_begin_with` list but definitely not mobile only. Maybe the situation is differnt in some other countries which have dedicated area code for mobile numbers.

I am not sure how often people need to know "whether a number is a moible number". I imagine most users of this library care more about "is this number a legit phone number". Right now by default `allowLandline` is off. Maybe the meta data format can be `less mobile number oriented`?

**Comment by Bossa573** [comment]
Thanks for the comment.

The `allowLandline` hack is basically skipping the `mobile_begin_with` validation, however, "Not validating the start-with digits" does not essentially equal to "allowing landline phone number", this UK issue is the perfect example. 

There are quite a number of voices about "converting this module to become the more generic purpose, rather than mobile phone number oriented", which I totally understand this as it contradicts to the npm package name `phone`. (I'm not the original author of this module)

If there is a future major bump (version 3.x), definitely we should make it more general-purposed, however, at the moment we do not have extra bandwidth to rewrite the module. For the current version 2.x, I do not recommend adding length = 7, 9 to UK phone number as it will break the current behavior that "validating mobile phone number only", which is the main purpose we originally created this module.

**Comment by keningharryscom** [comment]
👌 closing the pr to include 7 and 9 digits numbers in UK. We will have to override this in our own code then.

btw, right now we will have to turn on `allowLandline` (which is basically `do not check mobile_begin_with`) when we use the library, since some of the legit area code are missing from `mobile_begin_with`. For example, in the US, 220 is not listed as `mobile_begin_with` but it's a legit area code (and it's also a legit mobile area code, if you check http://www.cell-phone-list.net/area-code-list.html). Without `allowLandline=true`, the library will reject phone number with area code 220.
