### ISSUE TITLE
Wrong behaviour with RUS mobile oprator

### ISSUE THREAD

**Issue by pantonie** [AfterShip/phone#174]
Hi, I have an issue with russian mobile operator whose code is 999. In case I add trailing digit to phone number I get phone number with missed "9" in the beginning. E.g.  for +799912345678 the result will be +79912345678.

**Comment by Bossa573** [comment]
for the phone number `+799912345678`
`+7`: Russia
`99912345678`: your phone number

Because according to the current data set,
![image](https://user-images.githubusercontent.com/1013526/73327167-d89ac680-428f-11ea-9959-220f999f1564.png)
A Russian mobile phone number would be started with `9` or `495` and with 10 digits.

If you find this is incorrect (say started with `9` and have 11 digits, which is what your sample phone number is), can you provide related documents?

**Comment by pantonie** [comment]
Hi,
Thank you for response.

According to your configuration phone number with 11 digits should be wrong. So phone('+799912345678') should return empty array, but instead library silently cut one digit and returns wrong number. E.g. phone('+791212345678') === [] but phone('+799912345678') === ["+79912345678", "RUS"]. The same behaviour is for all mobile numbers '+799?12345678'.

**Comment by Bossa573** [comment]
Hello @pengzihe 
I have investigated the code, for this case:

for phone number: `+799912345678`

1. The module will first try to match all perfect match countries, which is none, as the config doesn't allow +7 and followed by 11 digits.
2. And then the module will try to look for possible countries, the module will consider the phone number structure as follow: 
```
+7: country code
9: trunk code
9912345678: phone number
```
and then it will remove the trunk code , so that it becomes `+79912345678`.

Considering the phone inside test cases, like `+7(8)9234567890`, the `(8)` should not be part of the E.163 format phone number and being considered as a trunk code, and be removed.

If you find there is indeed a Russian phone number with 11-digit AND without trunk code, please let me know together with related documents and let me know, I'll update the iso3166 data

**Comment by pantonie** [comment]
Hi,

Thank you very much for explanation of code logic. I will consider this behaviour in my code.

**Comment by Bossa573** [comment]
Thank you and I'll close this ticket for now, please reopen if needed
