### ISSUE TITLE
Singapore landlines do not start with '5'

### ISSUE THREAD

**Issue by gnoyixiang** [AfterShip/phone#186]
Hi, thanks for creating this useful and lightweight library. I have an issue with validating Singapore landlines. The logic currently accepts numbers starting with '5', which is not the case for Singapore.

Here's what was extracted from [Wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Singapore): 

> Number ranges
> 3xxx xxxx - Business and Corporate IP Telephony Services[2]
> 
> 6xxx xxxx - Public Switched Telephone Network (PSTN) and Residential IP Telephony Services
> 
> 8zxx xxxx - Mobile , Data Services , New Numbers and Prepaid Numbers
> 
> 9yxx xxxx - Mobile, Data Services and Pager (until May 2012)

This is the result I got when validating the phone number:
```
phone('55432109', 'SG', true)
(2) ["+6555432109", "SGP"]
phone('55432109', 'SGP', true)
(2) ["+6555432109", "SGP"]
```

**Comment by Bossa573** [comment]
Sorry for the misleading readme,
the third parameter `allowLandLine` is precisely `ignore ALL phone number initial checking logic`, 
instead of validating if a phone number is actually with the correct landline phone number format of that country.

And in fact the library does NOT contain landline phone number format data, and it can never do a real validation of landline phone number.

I will improve the readme for this one.
