### ISSUE TITLE
German land line phones get rejected

### ISSUE THREAD

**Issue by relief-melone** [AfterShip/phone#207]
according to the iso3166Data.js allowed number lengths for country code 49 are 10 and 11 but

+49 7654 12345

would also be perfectly valid. I'd make a pull request directy but was not sure if changing the iso3166Data.js would be all that's needed. Maybe this way is quicker ;)

**Comment by Bossa573** [comment]
1. The number length is excluding the country code, i.e. only counting the part `7654 12345`, which is not 10 nor 11.
2. The number detecting mechanism is bound by `mobile_begin_with`
![image](https://user-images.githubusercontent.com/1013526/96529194-1a085180-12b7-11eb-9c98-21fc9ec8d037.png)
It validates the phone number prefix, which means it only allows the phone number starts with 15, 16, or 17
This is because the by default this module is meant to be used for detecting and formating `mobile` phone number.
If you want to work with landline phone number, you may want to set `allowLandline` to true:
https://github.com/AfterShip/phone#skipping-phone-number-initial-digit-checking
