### ISSUE TITLE
Omit wrong number

### ISSUE THREAD

**Issue by trungbkit** [AfterShip/phone#210]
I was trying to use the wrong Vietnamese phone number to validate. My phone is +849752xxxx2. When I call
```js
phone('+849752xxxx25');
```
It omitted the '9', became '+84752xxxx25'. It's different from my expectation. I expected it returned an empty array.

I think this line
```js
formatPhone = iso3166.country_code + formatPhone.replace(new RegExp(`^${iso3166.country_code}\\d`),'');
```
should be edited to 
```js
formatPhone = iso3166.country_code + formatPhone.replace(new RegExp(`^${iso3166.country_code}0`),''); // Only omit '0'
```

**Comment by trungbkit** [comment]
#211

**Comment by Bossa573** [comment]
1. `phone('+849752xxxx25')`

the phone number `9752xxxx25`, is a 10-digit phone number, you sure it's not typo? 
it's different from your sample statement `+849752xxxx2`, which `9752xxxx2` contains only 9 digits
From `./lib/iso3166Data.js`, the config only accept 9-digit phone number

![image](https://user-images.githubusercontent.com/1013526/97945763-73967300-1dc3-11eb-8f0e-ccb626807b71.png)

2. If you try with a 9-digit phone number, it works normally
![image](https://user-images.githubusercontent.com/1013526/97945792-8b6df700-1dc3-11eb-882b-d0826e77f54f.png)

The unexpected result is, if you provide +84 with a 10-digit phone number, 
the library will consider the first digit of the phone number is a thunk code, as by the config, 
viet nam mobile phone number should not have 10-digit.
If you think it's not correct, you may want to modify the config file instead.

**Comment by trungbkit** [comment]
Hi @Bossa573 
When we call `phone('+849752111125')`, I think it should return an empty array instead of omitting the `9`.
I also read the comment
```
// for some countries, the phone number usually includes one trunk prefix for local use
// The UK mobile phone number ‘07911 123456’ in international format is ‘+44 7911 123456’, so without the first zero.
// 8 (AAA) BBB-BB-BB, 0AA-BBBBBBB
// the numbers should be omitted in international calls
```
As I know, in Vietnam we can't omit any digit other than `0`.

**Comment by Bossa573** [comment]
@trungbkit 
no, the point is you provided 2 different samples in your ticket

# 9-digit phone number
+84 975211112

# 10-digit phone number
+84 9752111125

Which one is correct? or both correct?
If **10-digit** is correct and expected, please provide the related documentation, and modify the config file to make it supporting both **9** and **10** digit phone number instead

**Comment by Bossa573** [comment]
![Uploading image.png…]()

**Comment by Bossa573** [comment]
![image](https://user-images.githubusercontent.com/1013526/98068453-0eac4d00-1e97-11eb-886c-0b5508aa9872.png)

**Comment by trungbkit** [comment]
Only the 9-digit phone number is correct. So I expect it'll return an empty array (invalid phone number) when I call `phone('+849752xxxx25');`

**Comment by Bossa573** [comment]
You should not provide the unexpected different length of the phone number which is not supported by a particular country unless it is a thunk code at the front.
The library will not support the country-specific thunk code mechanism, and some countries do have thunk code other than zero. (Can check the broken test case of that PR) That's why the mobile can only try with the **best guess** and for some cases, it does format the phone number unexpectedly like this case.

The concept is, if the input contains a `plus` sign, it's assumed that the user should know the country of the phone number, but the length of the phone number is incorrect, the library could not tell it's thunk code issue, config issue, or simply wrong input. Therefore the output would become unexpected.

**Comment by Bossa573** [comment]
closing the ticket, please reopen if needed
