### ISSUE TITLE
Invalid italian mobile phone numbers erroneously flagged as valid

### ISSUE THREAD

**Issue by pietrom** [AfterShip/phone#220]
I'm using this very fun library in order to validate an italian phone number. I made many tests in my application and I found a *corner case* producing an erroneously response, according to the rules that are applied in my country.

Italian mobile phone numbers have `+39` country prefix and starts with the `3` digit. Number length should be 9 or 10 (as correctly stated in the library configuration).

So, I think that
```
phone('+3933812345678')
```
should return an empty array, because the provided number exceeds the max valid length (its length is 11).
Conversely, I obtain the following response:
```
["+393812345678", "ITA"]
```
There is a missing digit in the normalized number (using the last available library version, 2.4.20 at the moment).

I made many other tests with different phone numbers and found that the problem is related to the first digit **after** the "mobile first digit": numbers starting with `+3934` are correctly validated (e.g. `+3934712345678` is rejected as invalid, as expected).

I tried to find and fix the problem in my local copy of the library: it seems to be related to the statement
```
index.js # 78: formatPhone = iso3166.country_code + formatPhone.replace(new RegExp(`^${iso3166.country_code}\\d`),'');
```
which removes the country code (39) **AND** the first following digit, leaving the subsequent secondo 3 digit as first character after `39`:

* `3933812345678` --> `393812345678`, which is a **valid** italian mobile phone number and results in successful validation
* `3934712345678` --> `394712345678`, which is an **invalid** italian mobile phone number and results in unsuccessful validation, as expected

I tried commenting out the line above: my italy-related tests become green but a bunch of (four) other tests fail.

Can anyone to give me any suggestions about the approach I should use to fix the problem?

In attachment an additional test file you can simply drop in the `__tests__` directory in order to reproduce the issue. You should rename it in order to make it available to jest...

Thank you very much in advance - and for the amazing job you already did.

[italy.js.txt](https://github.com/AfterShip/phone/files/5973161/italy.js.txt)

**Comment by Bossa573** [comment]
Hello,

thank you for the detailed report,
and yes, the issue is due to `index.js # 78`, 
if there is a plus sign (`+`) but unable to match any country directly,
the module will try to remove 1 digit from the phone number part (excluding the country code),
therefore `+39 33812345678` will become `+39 3812345678`,
this is for trying to remove the thunk code from the phone number (which the trunk code should not be included if there is a country code)

While the existing logic would be a bit clumsy as false positive might happen like this case,
as you mentioned, the current logic cannot be removed directly as:
1. It breaks some phone number detection (as stated in the code's comment)
2. It could break existing applications that rely on this logic (including the false positive detection)

In the upcoming new major version (3.x.x),
I'm considering adding more options for toggling such behavior,
however, maybe it's not very suitable to extend the current interface (`phone(phone: String, [country: string, allowLandline: Boolean])`)

For your case, you might want to consider using own fork temporarily, what do you think?

**Comment by Bossa573** [comment]
please reopen the issue if needed
