### ISSUE TITLE
Conforming works without region, but not with

### ISSUE THREAD

**Issue by mrgrue** [AfterShip/phone#257]
If I pass in an ARG phone with just the phone number, I get a good result:

```
> phone('+54 9 11 6673 9093')
[ '+541166739093', 'ARG' ]
```

However, if I pass in the region, I get a bad result:

```
> phone('+54 9 11 6673 9093', 'ARG')
[]
```

This is using Node v12.16.3 and Phone 2.4.22.

**Comment by Bossa573** [comment]
it's because the digit `9` after `+54` is not a valid usage for international inbound SMS for ARG, please see https://github.com/AfterShip/phone/pull/253 for the detail explanation, thank you

**Comment by Bossa573** [comment]
and also because if you do not pass country code as the second parameter, the module treat that `9` as a thunk code and try to detect the phone number by removing it, this logic doesn't apply if the country code provided
(please refer to this logic: https://github.com/AfterShip/phone#trunk-code-detection-logic)
