### ISSUE TITLE
Can't get strictDetection to work as intended

### ISSUE THREAD

**Issue by jodhman** [AfterShip/phone#326]
Hi! I'm currently using this library the following way:
`
const phoneNumber = phone(value, {
        country: 'FR',
        strictDetection: true,
      });
`
but the Trunk Code Detection Logic still appears to be running.

The number `0706336876` (Swedish local format) returned `isValid: true` for country France.

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L599

because the number `0706336876` is indeed a valid French mobile phone number according to the library data.

the "strictDetection" works when there is a country code before the phone number.
https://github.com/AfterShip/phone#6-trunk-code-detection-logic
