### ISSUE TITLE
Chinese cell phone numbers will be recognized as US cell phone numbers

### ISSUE THREAD

**Issue by wt-fangying** [AfterShip/phone#354]
The first 1 of a Chinese cell phone number is treated as +1 by default, so much so that an 11-digit Chinese cell phone number becomes a 10-digit US number. Whether or not it is preceded by the +1 symbol

**Comment by Bossa573** [comment]
if you know the phone number is a Chinese phone number, 
please append `+86` before the phone number, or specify "CHN" in `options.country`.

The library does not have the capability to determine if you only provide an 11-digit string because it can potentially match many countries' formats,
and therefore if there is no country code provided, 
the library will simply assume the phone number is a USA phone number.

See https://github.com/AfterShip/phone#3-without-country-code-and-no-phone-prefix for detail.

**Comment by wt-fangying** [comment]
In my problem, a Chinese phone number like 17862571736 is recognized as a US number when testing +1 17862571736, the verification should recognize the 1 of the number as a US +1, but +86 17862571747 is recognized as a Chinese number. I hope the result is that +1 17862571736 should not pass.

**Comment by Bossa573** [comment]
`+117862571736` works because of truck code detection logic, please check https://github.com/AfterShip/phone#6-trunk-code-detection-logic
You can see from the result, it became `+17862571736` automatically

**Comment by wt-fangying** [comment]
Thank you very much, the problem has been solved. I apologize for disturbing you due to my oversight of not checking the documentation carefully.
