### ISSUE TITLE
Bug in Finnish numbers

### ISSUE THREAD

**Issue by ambodi** [AfterShip/phone#38]
Just found out a bug in your package:

```javascript 
  var phone = require('phone')
   phone('+358 (0) 10 44 88 000') // []
   phone('+358104488000')    // []
```

This is Nokia's office number in Helsinki, Finland and it's a valid number. It surprisingly returns an empty array.

**Comment by teddychan** [comment]
Here is the FINLAND mobile phone number setting in our lib.

```
{alpha2: "FI", alpha3: "FIN", country_code: "358", country_name: "Finland", mobile_begin_with: ["4", "5"], phone_number_lengths: [9]}
```

https://en.wikipedia.org/wiki/Telephone_numbers_in_Finland

the mobile number should begin with `4` or `5`
while your example is begin with `1`

notice that our lib is aim to identify if it is a mobile phone number in order to send out the SMS.
