### ISSUE TITLE
[phone number format] 

### ISSUE THREAD

**Issue by koteesy** [AfterShip/phone#407]
### Country/Region

RUS

### Sample input with real phone format

8 952 666 66 66

### Reference docs/website

Hello! Thanks for great library. 

Some of phones which i try to validate, are valid, but library does know about that, for example, let's take a real valid number, and i have no problem with that: is valid
```
+7-952-666-66-66
```

But if i try to validate number without plus, i got not valid result, but it should be valid, because they're identical
```
7-952-666-66-66
```

Same situation with phone format like
```
8-952-666-66-66
```

We also got not valid result, but it should be valid, because for RU we allow to use one of these 2 variants: +7 and 8

Reference: https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia

### Mobile phone number

- [X] I confirmed that the provided sample is a mobile phone number.

**Comment by Bossa573** [comment]
1. about the plus sign, please refer to this section of the readme:
https://github.com/AfterShip/phone?tab=readme-ov-file#4-with-country-code--phone-prefix-but-no--sign
it is expected behavior. If you know your phone number include the country code, please make sure you include the plus sign, otherwise it must go wrong unless it's a US phone number

2. about `8`
I searched some other website, however it's unable to find such result,
[some source](https://www.sent.dm/resources/RU) stated that prefixed with 8 is not for mobile phone number
and also from the wiki page, 8 is not a country code, it's only the trunk prefix, which would not be the scope of this library.
